# geometry
GLYPH_WIDTH = 1000
GLYPH_HEIGHT = 1000

HUI_FINGER_WIDTH = 360
HUI_FINGER_HEIGHT = 435
NUMBER_WIDTH = 360
NUMBER_HEIGHT = 435
XIAN_FINGER_WIDTH = 720
XIAN_FINGER_HEIGHT = 515
N_PLACEHOLDER_WIDTH = 305
N_PLACEHOLDER_HEIGHT = 370

# data
NUMBER_DATA_PATH = './jsons/number.json'
HUI_FINGER_DATA_PATH = './jsons/hui_finger.json'
XIAN_FINGER_DATA_PATH = './jsons/xian_finger.json'

FONT_PATH = './jianzipu.otf'