from collections import defaultdict
from dataclasses import dataclass, field
from itertools import product

import yaml

from .constants import (
    GLYPHS,
    JIANZI_ORDER,
    PATH_TO_FEA,
    PATH_TO_FEATURES,
    CN_from_EN,
    EN_from_CN,
)
from .layout import LayoutNode, get_all_layouts, parse_figma
from .metadata import WIDTH
from .parser import ParseNode

SF_d = {
    "": "",
    "hf": "@hf_md",
    "hn1": "@hn_md",
    "hn1-hn2": "@hn_sm @hn_sm",
    "xf": "@xf_md",
    "xn1": "@xn_md",
    "xn1-xn2": "@xn_sm @xn_sm",
    "sf": "@sf_md",
}

class Template:
    def __init__(self, values):
        self.values = values
    def optional(self):
        return Template([""] + self.values)
    def __add__(self, other):
        values = []
        for a, b in product(self.values, other.values):
            value = " ".join([a, b]).strip()
            values.append(value)
        return Template(sorted(set(values)))
    def __repr__(self):
        return str(self.values)

@dataclass
class Lookup:
    name: str
    rules: list[str] = field(default_factory=list)

    def to_str(self):
        rules = "".join(f"\t{rule}\n" for rule in self.rules)
        return f"lookup {self.name} {{\n{rules}}} {self.name};\n"

@dataclass
class Feature:
    name: str
    lookups: list[Lookup] = field(default_factory=list)

    def to_str(self):
        lookups = "".join(f"\tlookup {lookup.name};\n" for lookup in self.lookups)
        return "\n".join(lookup.to_str() for lookup in self.lookups) + "\n" + f"feature {self.name} {{\n{lookups}}} {self.name};\n"

def import_features(file=PATH_TO_FEATURES):
    with open(file, "r") as f:
        features = yaml.safe_load(f)
        macros = {}
        rule_templates = {}
        for k, v in features.items():
            if k.startswith("@"):
                macros[k] = v
            else:
                rule_templates[tuple(k.split(" "))] = v
    return macros, rule_templates

def gen_macros():
    # glyphclass for hanzi
    hanzi_macros = defaultdict(list)
    for glyphname, tag in zip(GLYPHS.GlyphName, GLYPHS.GlyphTag):
        hanzi_macros[f"@{tag}"].append(glyphname)
    # glyphclass for jianzi
    scope = ["hf", "xf", "sf", "n"] # NOTE: currently we only support these 4 scopes
    variant = ["tn", "sm", "md", "lg"]
    jianzi_macros = {f"@{tag}_{var}": [] for tag, var in product(scope, variant)}
    for glyphname in JIANZI_ORDER.keys():
        glyph, var = glyphname.split(".")
        tag = GLYPHS[GLYPHS.GlyphName == glyph].GlyphTag.item()
        # print(tag)
        if (tag in scope) and (var in variant):
            jianzi_macros[f"@{tag}_{var}"].append(glyphname)
    ## numbers
    n_d = {
        "@hn": "@n",
        "@xn": "@n",
        "@hn_sm": "@n_sm",
        "@hn_md": "@n_md",
        "@xn_sm": "@n_sm",
        "@xn_md": "@n_md",
    }
    macros = hanzi_macros | jianzi_macros | n_d
    return {k: v for k, v in macros.items() if v}

def gen_rule_template():
    # rule template for SF
    hf = Template(["hf"])
    hn = Template(["hn1", "hn1-hn2"])
    sf = Template(["sf"]).optional()
    xf = Template(["xf"])
    xn = Template(["xn1", "xn1-xn2"])

    hfp = hf + hn.optional()
    xfp = xf + xn.optional()
    SF = hfp.optional() + sf.optional() + xfp.optional()

    rule_templates = {}
    for key in SF.values:
        if key:
            value = " ".join(SF_d[k] for k in key.split())
            key = key.replace("-", " ")
            # break
            rule_templates[tuple(key.split())] = value
    rule_templates = dict(sorted(rule_templates.items(), key=lambda x: x[0],reverse=True))
    return rule_templates

def write_template(macros, rule_templates, file=PATH_TO_FEATURES):
    with open(file, "w") as f:
        f.write("# This file is auto-generated by jianzipu/feature.py, do not edit manually.\n")
        f.write("# macros\n")
        lines = []
        for key, value in macros.items():
            if isinstance(value, list):
                value = [f"'{v}'" for v in value]
                line = f"'{key}': [{','.join(value)}]"
            else:
                line = f"'{key}': '{value}'"
            lines.append(line)
        f.write("\n".join(lines))

        f.write("\n\n")

        lines = []
        for tags, template in rule_templates.items():
            template_ = []
            for s in template.split(" "):
                template_.append(f"'{s}'")
            line = f"{' '.join(tags)}: [{','.join(template_)}]"
            lines.append(line)
        f.write("# rule templates\n")
        f.write("\n".join(lines))
    return

def write_macros(macros):
    lines = []
    for key, value in macros.items():
        if isinstance(value, list):
            line = f"{key}=[{' '.join(value)}];"
        else:
            line = f"{key}={value};"
        lines.append(line)
    fea_text = "\n".join(lines)
    return fea_text

def write_sub_rules(rule_templates: dict[tuple[str, ...], list]):
    '''Write all sub rules according to the rule templates.'''
    lookups = []
    rules = []
    # many hanzi to one jianzi 
    for glyphname in GLYPHS.GlyphName.tolist():
        glyphname_cn = CN_from_EN[glyphname]
        if len(glyphname_cn) > 1: # is ligature
            glyph_out = glyphname
            glyphs_in = ' '.join(EN_from_CN[g] for g in glyphname_cn)
            rule = f"sub {glyphs_in} by {glyph_out};"
            rules.append(rule)
    lookup = Lookup(name="many2one", rules=rules)
    lookups.append(lookup)

    # lookups for variants
    rules = [
        "sub @hf by @hf_md;",
        "sub @xf by @xf_md;",
        "sub @n by @n_md;",
    ]
    lookup = Lookup(name="md", rules=rules)
    lookups.append(lookup)
    rules = [
        "sub @hf by @hf_sm;",
        # "sub @xf by @xf_sm;", # TODO not all xf has sm variant
        "sub @n by @n_sm;",
    ]
    lookup = Lookup(name="sm", rules=rules)
    lookups.append(lookup)

    # jianzi to jianzi variant
    rules = []
    for tags, rule_template in rule_templates.items():
        rule = "sub"
        for tag, glyphclass in zip(tags, rule_template):
            tag = tag.replace("1", "").replace("2", "") # remove number suffix in hn1, hn2, xn1, xn2
            suffix = glyphclass.split("_")[-1]
            rule += f" @{tag}' lookup {suffix}"
        rule += ";"
        rules.append(rule)
    lookup = Lookup(name="jianzi2variant", rules=rules)
    lookups.append(lookup)

    feature = Feature(name="liga", lookups=lookups)
    return feature


def write_pos_rule(layout: LayoutNode, rule_templates: dict[tuple[str, ...], str]):
    '''Write a pos rule for a given layout node according to the rule template it fits.'''
    tags = layout.get_children_tags()
    rule_template = rule_templates[tags]
    rule = "pos"
    for node, term in zip(layout.children.values(), rule_template):
        x,y,w,h = node.area.xywh
        # NOTE: transform from layout coordinate system (y down) to glyph coordinate system (y up), remember the xywh here is relative to the design box, whose origin is the top-left corner (0,WIDTH) in glyph coordinate system 
        dx,dy = x, WIDTH-(h+y)
        if node.name == "":
            rule += f" {term}' <{dx} {dy} 0 0>"
        else:
            rule += f" {node.name_en}.{term[-2:]}' <{dx} {dy} 0 0>"
    rule += ";"
    return rule

def find_matching_layout(puzi: ParseNode, all_layouts: list[LayoutNode]):
    """Return all layouts matching a parse tree.

    Match rules:
    1) parse_tree tags must be a subset of layout tags.
    2) For each jianzi in parse_tree, layout name is wildcard when "",
       otherwise it must equal jianzi.name.
    """
    puzi_tag_set = set(puzi.get_children_tags())
    matched_layouts: list[LayoutNode] = []

    for layout in all_layouts:
        layout_tag_set = set(layout.get_children_tags())
        if not puzi_tag_set.issubset(layout_tag_set):
            continue

        if all(
            layout.children[jianzi.tag].name == ""
            or layout.children[jianzi.tag].name == jianzi.name
            for jianzi in puzi.children.values()
        ):
            matched_layouts.append(layout)

    if not matched_layouts:
        raise ValueError("No matching layout found, have you implemented in figma.css?")

    return next(
        (layout for layout in matched_layouts if set(layout.get_children_tags()) == puzi_tag_set),
        matched_layouts[0],
    )

def main():
    # write features.fea
    # macros = import_macros()
    macros = gen_macros()
    rule_templates = gen_rule_template()
    write_template(macros, rule_templates)

    macros, rule_templates = import_features()
    form_templates, layout_templates, component_dict = parse_figma()
    all_layouts = get_all_layouts(form_templates, layout_templates, flatten=True)

    with open(PATH_TO_FEA, "w") as f:
        # macros
        f.write(write_macros(macros) + "\n\n")
        # sub rules
        rules = ""
        feature_liga = write_sub_rules(rule_templates)
        # sub rules goes to liga feature
        f.write(feature_liga.to_str())
        f.write('\n')

        # pos rules
        lookups = []
        rules = []
        for layout in all_layouts:
            rule = write_pos_rule(layout, rule_templates)
            rules.append(rule)
        lookup = Lookup(name="jzp_pos_rules", rules=rules)
        lookups.append(lookup)

        # pos rules goes to kern feature
        feature_kern = Feature(name="kern", lookups=lookups)
        f.write(feature_kern.to_str())
        f.write('\n')

if __name__ == "__main__":
    main()
