from itertools import product

import yaml

from .constants import GLYPH_ORDER, GLYPHS, PATH_TO_FEA, PATH_TO_FEATURES
from .layout import LayoutNode, get_all_layouts, parse_figma
from .metadata import WIDTH
from .parser import ParseNode

SF_d = {
    "": "",
    "hf": "@hf_md",
    "hn1": "@hn_md",
    "hn1-hn2": "@hn_sm @hn_sm",
    "xf": "@xf_md",
    "xn1": "@xn_md",
    "xn1-xn2": "@xn_sm @xn_sm",
    "sf": "@sf_md",
}

class Template:
    def __init__(self, values):
        self.values = values
    def optional(self):
        return Template([""] + self.values)
    def __add__(self, other):
        values = []
        for a, b in product(self.values, other.values):
            value = " ".join([a, b]).strip()
            values.append(value)
        return Template(sorted(set(values)))
    def __repr__(self):
        return str(self.values)

def import_features(file=PATH_TO_FEATURES):
    with open(file, "r") as f:
        features = yaml.safe_load(f)
        macros = {}
        rule_templates = {}
        for k, v in features.items():
            if k.startswith("@"):
                macros[k] = v
            else:
                rule_templates[tuple(k.split(" "))] = v
    return macros, rule_templates

def gen_macros():
    scope = ["hf", "xf", "sf", "n"] # NOTE: currently we only support these 4 scopes
    variant = ["tn", "sm", "md", "lg"]
    macros = {f"@{tag}_{var}": [] for tag, var in product(scope, variant)}
    for glyphname in GLYPH_ORDER.keys():
        glyph, var = glyphname.split(".")
        tag = GLYPHS[GLYPHS.GlyphName == glyph].GlyphTag.item()
        # print(tag)
        if (tag in scope) and (var in variant):
            macros[f"@{tag}_{var}"].append(glyphname)
    # numbers
    n_d = {
        "@hn_sm": "@n_sm",
        "@hn_md": "@n_md",
        "@xn_sm": "@n_sm",
        "@xn_md": "@n_md",
    }
    macros.update(n_d)
    return {k: v for k, v in macros.items() if v}

def gen_rule_template():
    # rule template for SF
    hf = Template(["hf"])
    hn = Template(["hn1", "hn1-hn2"])
    sf = Template(["sf"]).optional()
    xf = Template(["xf"])
    xn = Template(["xn1", "xn1-xn2"])

    hfp = hf + hn.optional()
    xfp = xf + xn.optional()
    SF = hfp.optional() + sf.optional() + xfp.optional()

    rule_templates = {}
    for key in SF.values:
        if key:
            value = " ".join(SF_d[k] for k in key.split())
            key = key.replace("-", " ")
            # break
            rule_templates[tuple(key.split())] = value
    return rule_templates

def write_template(macros, rule_templates, file=PATH_TO_FEATURES):
    with open(file, "w") as f:
        f.write("# This file is auto-generated by jianzipu/feature.py, do not edit manually.\n")
        f.write("# macros\n")
        lines = []
        for key, value in macros.items():
            if isinstance(value, list):
                value = [f"'{v}'" for v in value]
                line = f"'{key}': [{','.join(value)}]"
            else:
                line = f"'{key}': '{value}'"
            lines.append(line)
        f.write("\n".join(lines))

        f.write("\n\n")

        lines = []
        for tags, template in rule_templates.items():
            template_ = []
            for s in template.split(" "):
                template_.append(f"'{s}'")
            line = f"{' '.join(tags)}: [{','.join(template_)}]"
            lines.append(line)
        f.write("# rule templates\n")
        f.write("\n".join(lines))
    return

def write_macros(macros):
    lines = []
    for key, value in macros.items():
        if isinstance(value, list):
            line = f"{key}=[{' '.join(value)}];"
        else:
            line = f"{key}={value};"
        lines.append(line)
    fea_text = "\n".join(lines)
    return fea_text

def write_pos_rule(layout: LayoutNode, rule_templates: dict[tuple[str, ...], str]):
    tags = tuple(layout.get_children_tags())
    rule_template = rule_templates[tags]
    rule = []
    for node, term in zip(layout.children.values(), rule_template):
        x,y,w,h = node.area.xywh
        # NOTE: transform from layout coordinate system (y down) to glyph coordinate system (y up), remember the xywh here is relative to the design box, whose origin is the top-left corner (0,WIDTH) in glyph coordinate system 
        dx,dy = x, WIDTH-(h+y)
        if node.name == "":
            rule.append(f"{term}' <{dx} {dy} 0 0>")
        else:
            rule.append(f"{node.name_en}.{term[-2:]}' <{dx} {dy} 0 0>")
    return "pos " + " ".join(rule)

def find_matching_layout(puzi: ParseNode, all_layouts: list[LayoutNode]):
    """Return all layouts matching a parse tree.

    Match rules:
    1) parse_tree tags must be a subset of layout tags.
    2) For each jianzi in parse_tree, layout name is wildcard when "",
       otherwise it must equal jianzi.name.
    """
    puzi_tag_set = set(puzi.get_children_tags())
    matched_layouts: list[LayoutNode] = []

    for layout in all_layouts:
        layout_tag_set = set(layout.get_children_tags())
        if not puzi_tag_set.issubset(layout_tag_set):
            continue

        if all(
            layout.children[jianzi.tag].name == ""
            or layout.children[jianzi.tag].name == jianzi.name
            for jianzi in puzi.children.values()
        ):
            matched_layouts.append(layout)

    if not matched_layouts:
        raise ValueError("No matching layout found, have you implemented in figma.css?")

    return next(
        (layout for layout in matched_layouts if set(layout.get_children_tags()) == puzi_tag_set),
        matched_layouts[0],
    )

def main():
    # write features.fea
    # macros = import_macros()
    macros = gen_macros()
    rule_templates = gen_rule_template()
    write_template(macros, rule_templates)

    macros, rule_templates = import_features()
    form_templates, layout_templates, component_dict = parse_figma()
    all_layouts = get_all_layouts(form_templates, layout_templates, flatten=True)

    with open(PATH_TO_FEA, "w") as f:
        f.write(write_macros(macros) + "\n")
        rules = ""
        lookup_pos_name = "jzp_pos_rules"
        for layout in all_layouts:
            rule = write_pos_rule(layout, rule_templates)
            rules += f"\t{rule};\n"
        lookup_pos = f"lookup {lookup_pos_name} {{\n{rules}}} {lookup_pos_name};"
        f.write('\n')
        f.write(lookup_pos)
        f.write('\n')

        feature_kern = f"feature kern {{\n\tlookup {lookup_pos_name};\n}} kern;"
        f.write('\n')
        f.write(feature_kern)
        f.write('\n')

if __name__ == "__main__":
    main()
